# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ManyToManyField(blank=True, to='images.Comment'),
        ),
    ]
