# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 14:59
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_remove_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
